######################################################################
# Automatically generated by qmake (3.1) Fri Nov 27 15:21:34 2020
######################################################################

TEMPLATE = app
TARGET = videoplayer
QT += core widgets multimediawidgets multimedia

SOURCES += main.cpp \
	MainWindow.cpp \
	VideoWidget.cpp

HEADERS += MainWindow.h \
	VideoWidget.h

# Directories
